const WA_MSG = encodeURIComponent("Hola vi que eres aliado de Asobares y necesito tus servicios");
export const waLink = (phone) => `https://wa.me/57${phone}?text=${WA_MSG}`;
export const callLink = (phone) => `tel:+57${phone}`;

export const ALLIES = [
  {
    id: 1,
    name: "Siigo",
    benefit: "Sistema POS para su establecimiento — 40% descuento en edición especial y 10% de inicio para afiliados",
    phone: "3057324247",
    email: "juliet.quintian@siigo.com",
    logo: "https://asobares.org/wp-content/uploads/2025/09/LOGO-SIIGO-CELESTE-4.png",
  },
  {
    id: 2,
    name: "Hielo Iglu",
    benefit: "Descuento en suministro de Hielo Estándar y Premium",
    phone: "3136779254",
    email: "gerenciabogota@hieloiglu.com",
    logo: "https://asobares.org/wp-content/uploads/2025/09/HIELO-IGLU.png",
  },
  {
    id: 3,
    name: "Matipost",
    benefit: "Manillas para eventos — 5% de descuento en portafolio exclusivo",
    phone: "3136107202",
    email: "ventas@manillaparaeventos.com",
    logo: "https://asobares.org/wp-content/uploads/2025/09/MANILLAS.png",
  },
  {
    id: 4,
    name: "Giovanni López",
    benefit: "25% de descuento en prendas de vestir de diseñador para afiliados",
    phone: "3167417044",
    email: "giolopez@giovannilopez.com",
    logo: "https://asobares.org/wp-content/uploads/2026/04/Giovanni-Lopez.jpg-scaled.jpeg",
  },
  {
    id: 5,
    name: "OSA — Sayco y Acinpro",
    benefit: "Pago de derechos de autor con tarifas preferenciales para afiliados",
    phone: "3102040740",
    email: "director.zonauno@saycoacimpro.org.co",
    logo: "https://asobares.org/wp-content/uploads/2025/09/OSA.png",
  },
  {
    id: 6,
    name: "Funnel Chat",
    benefit: "Plataforma de WhatsApp especializada para marketing",
    phone: "3144087079",
    email: null,
    logo: "https://asobares.org/wp-content/uploads/2026/03/aliados-web_Mesa-de-trabajo-1-copia-3-750x412.png",
  },
  {
    id: 7,
    name: "SLS Idiomas",
    benefit: "Inglés especializado en servicio — $22.000 por hora",
    phone: "3005017043",
    email: "cnieto@sls-idiomas.com",
    logo: "https://asobares.org/wp-content/uploads/2025/09/SLS.png",
  },
  {
    id: 8,
    name: "Balzak",
    benefit: "Dotación especializada para su negocio — 8% de descuento",
    phone: "3175753305",
    email: null,
    logo: "https://asobares.org/wp-content/uploads/2026/03/aliados-web_Mesa-de-trabajo-1-copia-23-750x412.png",
  },
  {
    id: 9,
    name: "El Empleo.com",
    benefit: "Plataforma de búsqueda de colaboradores — 1 mes de publicaciones gratis",
    phone: "3192732560",
    email: null,
    logo: "https://asobares.org/wp-content/uploads/2026/03/es-CO_ee_logo_seo.png",
  },
  {
    id: 10,
    name: "Mi Elegido VIP",
    benefit: "Conductores elegidos para sus clientes — 10% de descuento y 5% de rentabilidad por contratación",
    phone: "3114664070",
    email: "info@mielegidovip.com",
    logo: "https://asobares.org/wp-content/uploads/2026/03/aliados-web_Mesa-de-trabajo-1-copia-20-750x412.png",
  },
  {
    id: 11,
    name: "Cortes Romero y Asociados",
    benefit: "Asesoría en derecho laboral para su establecimiento",
    phone: "3002985240",
    email: "administrativa@cortesromero.com",
    logo: "https://asobares.org/wp-content/uploads/2025/09/CORTES-ROMERO-750x189.png",
  },
  {
    id: 12,
    name: "Manchego Agencia de Seguros",
    benefit: "Pólizas para eventos y establecimientos — hasta 25% de descuento",
    phone: "3115983068",
    email: "gerenteg.manchego@gmail.com",
    logo: "https://asobares.org/wp-content/uploads/2025/09/MANCHEGO-750x264.png",
  },
  {
    id: 13,
    name: "Coingenierias",
    benefit: "Diagnósticos acústicos gratuitos — 5% en compra de productos o insonorización de establecimientos",
    phone: "3118367765",
    email: "info@coingenierias.com",
    logo: "https://asobares.org/wp-content/uploads/2026/03/aliados-web_Mesa-de-trabajo-1-copia-2-750x412.png",
  },
  {
    id: 14,
    name: "Cluvi",
    benefit: "Menús especializados y análisis de negocio especializados",
    phone: "3044426160",
    email: "contact@cluvi.com",
    logo: "https://asobares.org/wp-content/uploads/2026/03/aliados-web_Mesa-de-trabajo-1-copia-21-750x412.png",
  },
  {
    id: 15,
    name: "RCN",
    benefit: null,
    phone: null,
    email: null,
    logo: "https://www.asomedios.com/wp-content/uploads/2017/08/logo-rcn.png",
  },
  {
    id: 16,
    name: "Grupo Lux — Postobón",
    benefit: null,
    phone: null,
    email: null,
    logo: "https://asobares.org/wp-content/uploads/2025/03/postobon.png",
  },
  {
    id: 17,
    name: "Assest Lia Consultores HSEQ",
    benefit: "Asesores expertos en SST — Capacitación en manipuladores de alimentos",
    phone: "3043932579",
    email: "Info@asesst.com.co",
    logo: "https://asesst.com.co/wp-content/uploads/2021/06/logo-sello.jpg",
  },
  {
    id: 18,
    name: "Grupo Mansión",
    benefit: "Electrodomésticos y equipamiento para establecimientos",
    phone: "3102530532",
    email: "ventas@grupomansion.com",
    logo: "https://asobares.org/wp-content/uploads/2026/03/aliados-web_Mesa-de-trabajo-1-copia-4-750x412.png",
  },
  {
    id: 19,
    name: "Pernod Ricard",
    benefit: null,
    phone: null,
    email: null,
    logo: "https://asobares.org/wp-content/uploads/2025/03/pernordricard.png",
  },
  {
    id: 20,
    name: "Diageo",
    benefit: null,
    phone: null,
    email: null,
    logo: "https://asobares.org/wp-content/uploads/2025/03/diageo.png",
  },
  {
    id: 21,
    name: "Bavaria",
    benefit: null,
    phone: null,
    email: null,
    logo: "https://www.bavaria.co/sites/g/files/seuoyk1666/themes/site/co_bavariacorp/Logo_new.png",
  },
  {
    id: 22,
    name: "Sulicor",
    benefit: null,
    phone: null,
    email: null,
    logo: "https://media.licdn.com/dms/image/v2/D4E03AQGtNk8tko-JPg/profile-displayphoto-scale_200_200/B4EZkrCQm5GUAY-/0/1757363637282?e=2147483647&v=beta&t=1C_981uSjVquyBXuog4STkFwW1ZcamoO9qU7FfYWwgM",
  },
  {
    id: 23,
    name: "Odir Certificaciones",
    benefit: "Certificación de redes eléctricas de establecimientos",
    phone: "3152339964",
    email: "paola.dias@odircertificaciones.com",
    logo: "https://media.licdn.com/dms/image/v2/C4E0BAQH9YxTDlvIBVg/company-logo_200_200/company-logo_200_200/0/1673560439416/odircertificaciones_logo?e=2147483647&v=beta&t=XdMq0ewaSWssyNJjcH8RLlZGXjAaeUrSLorLqMtSAD8",
  },
  {
    id: 24,
    name: "Asesoría Jurídica Asobares",
    benefit: "Asesoría legal especializada para afiliados",
    phone: "3203712784",
    email: "direccion.juridica@asobares.org",
    logo: null,
    isAsobares: true,
  },
  {
    id: 25,
    name: "Asesoría Contable Asobares",
    benefit: "Asesoría contable y financiera para afiliados",
    phone: "3192829939",
    email: "direccion.contable@asobares.org",
    logo: null,
    isAsobares: true,
  },
  {
    id: 26,
    name: "Asesoría Sanitaria Asobares",
    benefit: "Asesoría sanitaria para establecimientos",
    phone: "3108742581",
    email: "direccion.ejecutiva@asobares.org",
    logo: null,
    isAsobares: true,
  },
  {
    id: 27,
    name: "Asesoría Operativa Asobares",
    benefit: "Asesoría operativa para establecimientos afiliados",
    phone: "3232897493",
    email: "proyectos@asobares.org",
    logo: null,
    isAsobares: true,
  },
  {
    id: 28,
    name: "Bolsa de talento Cluster DJ",
    benefit: "Encuentra el DJ perfecto para tu establecimiento",
    logo: "https://www.clusterdj.co/img/logo_cluster_dj.png",
    link: "https://www.clusterdj.co/bolsa",
    isAsobares: true,
  },
];
